# Generated by Django 3.1.7 on 2021-09-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naoconformidade', '0003_nc_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nc',
            name='Situacao',
            field=models.CharField(blank=True, choices=[('Pendente', 'Pendente')], max_length=20, null=True),
        ),
    ]
