# Generated by Django 3.1.7 on 2021-09-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naoconformidade', '0006_auto_20210909_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='nc',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nc',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
