# Generated by Django 3.1.7 on 2021-09-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naoconformidade', '0007_auto_20210913_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nc',
            options={'verbose_name_plural': 'NC'},
        ),
    ]
