# Generated by Django 3.1.7 on 2021-09-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naoconformidade', '0008_auto_20210913_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nc',
            name='TN',
            field=models.FloatField(),
        ),
    ]
