# Generated by Django 3.1.7 on 2021-09-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naoconformidade', '0009_auto_20210913_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nc',
            name='TN',
            field=models.IntegerField(),
        ),
    ]
