# Generated by Django 3.1.7 on 2021-09-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naoconformidade', '0010_auto_20210914_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nc',
            name='TN',
            field=models.CharField(max_length=20),
        ),
    ]
